version: "3.8"
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todoapp




